checks:
  php:
    code_rating: true

filter:
  excluded_paths:
    - tests/*
    - vendor/*

build:

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

  environment:
    php: '8.3.17'

  dependencies:
    before:
      - composer install
      - mkdir -p build/logs

  tests:
    override:
      -
        command: 'phpdbg -qrr vendor/bin/phpunit --coverage-clover build/logs/clover.xml'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'clover'
